services:
  backend:
    build: backend
    container_name: app
    ports:
      - 8080:8080
    environment:
      - POSTGRES_DB=customer
    networks:
      - spring-postgres
  db:
    image: postgres
    restart: always
    container_name: db
    environment:
      - POSTGRES_DB=customer
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    expose:
      - 5432
    networks:
      - spring-postgres

networks:
  spring-postgres:

volumes:
  db-data: