spring:
  datasource:
    url: jdbc:postgresql://db:5432/customer
    username: compose-postgres
    password: compose-postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
      show_sql: true
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    operations-sorter: method
